version: '3.8'
services:
  frontend:
    build: ./frontend
    container_name: ileplaca_big_data_sharing_blockchain_container
    ports:
      - '5173:5173'
    volumes:
      - ./frontend:/app
      - /app/node_modules
    stdin_open: true